# Generated by Django 5.2.15 on 2026-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detection_direction_detection_flow_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='fire_intensity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='fire_temp_estimate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
