# Generated by Django 5.2.15 on 2026-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detection_fire_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='wind_beaufort_scale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='wind_direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
