# Generated by Django 5.2.15 on 2026-09-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_detection_wind_beaufort_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('drone_id', models.CharField(default='drone_01', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=50, unique=True)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('grid_size_deg', models.FloatField(default=0.001)),
            ],
        ),
        migrations.AlterField(
            model_name='detection',
            name='object_class',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detection',
            name='source',
            field=models.CharField(db_index=True, default='rgb', max_length=20),
        ),
        migrations.AlterField(
            model_name='detection',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='flight_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.flightpass'),
        ),
        migrations.AddField(
            model_name='detection',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detection.zone'),
        ),
        migrations.CreateModel(
            name='ZoneRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_label', models.CharField(max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('detection_count', models.IntegerField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('flight_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.flightpass')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.zone')),
            ],
        ),
    ]
